### ISSUE TITLE
Unable to execute the aspect

### ISSUE THREAD

**Issue by JSGette** [martis42/depend_on_what_you_use#160]
Looks like fetch of one of pip packages fails, even though I am able to locate it in /var/cache/pip folder.

```
ERROR: An error occurred during the fetch of repository 'dwyu_py_deps_pcpp':
   Traceback (most recent call last):
        File "/bazel_cache/output_user_root/61da6a75bcd751b8ee01d9c498363d41/external/rules_python/python/pip_install/pip_repository.bzl", line 438, column 13, in _whl_library_impl
                fail("whl_library %s failed: %s (%s)" % (rctx.attr.name, result.stdout, result.stderr))
Error in fail: whl_library dwyu_py_deps_pcpp failed: Looking in links: /var/cache/pip
Collecting pcpp==1.30
  File was already downloaded /var/cache/pip/pcpp-1.30-py2.py3-none-any.whl
 (Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/bazel_cache/output_user_root/61da6a75bcd751b8ee01d9c498363d41/external/rules_python/python/pip_install/parse_requirements_to_bzl/extract_single_wheel/__main__.py", line 4, in <module>
    main()
  File "/bazel_cache/output_user_root/61da6a75bcd751b8ee01d9c498363d41/external/rules_python/python/pip_install/parse_requirements_to_bzl/extract_single_wheel/__init__.py", line 68, in main
    whl = next(iter(glob.glob("*.whl")))
StopIteration
)
ERROR:<STRIPPED>/WORKSPACE:1474:18: fetching whl_library rule //external:dwyu_py_deps_pcpp: Traceback (most recent call last):
        File "/bazel_cache/output_user_root/61da6a75bcd751b8ee01d9c498363d41/external/rules_python/python/pip_install/pip_repository.bzl", line 438, column 13, in _whl_library_impl
                fail("whl_library %s failed: %s (%s)" % (rctx.attr.name, result.stdout, result.stderr))
Error in fail: whl_library dwyu_py_deps_pcpp failed: Looking in links: /var/cache/pip
Collecting pcpp==1.30
  File was already downloaded /var/cache/pip/pcpp-1.30-py2.py3-none-any.whl
 (Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/bazel_cache/output_user_root/61da6a75bcd751b8ee01d9c498363d41/external/rules_python/python/pip_install/parse_requirements_to_bzl/extract_single_wheel/__main__.py", line 4, in <module>
    main()
  File "/bazel_cache/output_user_root/61da6a75bcd751b8ee01d9c498363d41/external/rules_python/python/pip_install/parse_requirements_to_bzl/extract_single_wheel/__init__.py", line 68, in main
    whl = next(iter(glob.glob("*.whl")))
StopIteration
)
ERROR: /bazel_cache/output_user_root/61da6a75bcd751b8ee01d9c498363d41/external/depend_on_what_you_use/src/analyze_includes/BUILD:4:11: @depend_on_what_you_use//src/analyze_includes:lib depends on @dwyu_py_deps_pcpp//:pkg in repository @dwyu_py_deps_pcpp which failed to fetch. no such package '@dwyu_py_deps_pcpp//': whl_library dwyu_py_deps_pcpp failed: Looking in links: /var/cache/pip
Collecting pcpp==1.30
  File was already downloaded /var/cache/pip/pcpp-1.30-py2.py3-none-any.whl
 (Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/bazel_cache/output_user_root/61da6a75bcd751b8ee01d9c498363d41/external/rules_python/python/pip_install/parse_requirements_to_bzl/extract_single_wheel/__main__.py", line 4, in <module>
    main()
  File "/bazel_cache/output_user_root/61da6a75bcd751b8ee01d9c498363d41/external/rules_python/python/pip_install/parse_requirements_to_bzl/extract_single_wheel/__init__.py", line 68, in main
    whl = next(iter(glob.glob("*.whl")))
StopIteration
)
ERROR: Analysis of aspects '[//:aspect.bzl%your_dwyu_aspect] with parameters {} on <TARGET>' failed; build aborted: 
```

bazel version: 6.3.2
dowyu version: 0.13

**Comment by JSGette** [comment]
Okay, if I hack this script bazel_cache/output_user_root/61da6a75bcd751b8ee01d9c498363d41/external/rules_python/python/pip_install/parse_requirements_to_bzl/extract_single_wheel/__init__.py and just use direct path /var/cache/pip/pcpp-1.30-py2.py3-none-any.whl
instead of iterator it works

**Comment by martis42** [comment]
I am not sure if I will be able to help you. The error appears inside rules_python which is used to fetch the Python dependencies for DWYU. I did not implement this myself. Also I did not encounter this error yet.

Could you tell me the following, which maybe gives me more hints:
- which OS are you using
- which Python version are you using.
- Are you using the host Python interpreter or a hermetic Python toolchain offered by rules_python?
- Is your project settings its own rules_python version, or are you using the default version fetched by DWYU (which would be rules_python version 0.18.1 for DWYU 0.0.13).

**Comment by martis42** [comment]
rules_python 0.10.0 is indeed quite old.
Please try a recent version like 0.18.1.

**Comment by martis42** [comment]
closing due to no more feedback or help requests
